### PR TITLE
Add Tor SOCKS proxy

### PR DESCRIPTION
**Pull request by JonZeolla**

### CODE REVIEW

**Comment by jimmio** [comment]
After verifying that the environment variables were set, and checking the contents of the `tee`d files, I'm running into this:
```
vagrant@ubuntu-sandbox:~$ env | grep -i proxy
https_proxy=socks5h://127.0.0.1:9150
HTTPS_PROXY=socks5h://127.0.0.1:9150
HTTP_PROXY=socks5h://127.0.0.1:9150
http_proxy=socks5h://127.0.0.1:9150
ALL_PROXY=socks5h://127.0.0.1:9150
vagrant@ubuntu-sandbox:~$ curl icanhazip.com
1611090903 WARNING torsocks[37466]: [connect] Connection to a local address are denied since it might be a TCP DNS query to a local DNS server. Rejecting it for safety reasons. (in tsocks_connect() at connect.c:193)
curl: (7) Couldn't connect to server
vagrant@ubuntu-sandbox:~$ wget google.com
Error parsing proxy URL socks5h://127.0.0.1:9150: Unsupported scheme ‘socks5h’.
```

**Comment by jimmio** [comment]
I can ping `google.com` though, maybe because it's ICMP?
```
vagrant@ubuntu-sandbox:~$ ping google.com
PING google.com (172.217.12.238) 56(84) bytes of data.
64 bytes from iad30s15-in-f14.1e100.net (172.217.12.238): icmp_seq=1 ttl=63 time=9.12 ms
64 bytes from iad30s15-in-f14.1e100.net (172.217.12.238): icmp_seq=2 ttl=63 time=17.2 ms
64 bytes from iad30s15-in-f14.1e100.net (172.217.12.238): icmp_seq=3 ttl=63 time=16.0 ms
64 bytes from iad30s15-in-f14.1e100.net (172.217.12.238): icmp_seq=4 ttl=63 time=16.3 ms
64 bytes from iad30s15-in-f14.1e100.net (172.217.12.238): icmp_seq=5 ttl=63 time=16.2 ms
64 bytes from iad30s15-in-f14.1e100.net (172.217.12.238): icmp_seq=6 ttl=63 time=18.1 ms
^C
--- google.com ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5051ms
rtt min/avg/max/mdev = 9.123/15.491/18.076/2.934 ms
vagrant@ubuntu-sandbox:~$ wget google.com
Error parsing proxy URL socks5h://127.0.0.1:9150: Unsupported scheme ‘socks5h’.
```

**Comment by jimmio** [comment]
I thought maybe it was just `socks5h` but:
```
vagrant@ubuntu-sandbox:~$ export https_proxy=socks5://127.0.0.1:9150
vagrant@ubuntu-sandbox:~$ wget https://www.google.com
Error parsing proxy URL socks5://127.0.0.1:9150: Unsupported scheme ‘socks5’.
```

**Review by jimmio — CHANGES_REQUESTED** [review]
Noted some issues -- I'll dig a little to see if I can figure out what's going on.

**Comment by jimmio** [comment]
```
vagrant@ubuntu-sandbox:~$ torsocks curl icanhazip.com
1611091392 WARNING torsocks[37509]: [connect] Connection to a local address are denied since it might be a TCP DNS query to a local DNS server. Rejecting it for safety reasons. (in tsocks_connect() at connect.c:193)
curl: (7) Couldn't connect to server
vagrant@ubuntu-sandbox:~$ sudo torsocks curl icanhazip.com
1611091455 WARNING torsocks[37514]: [connect] Connection to a local address are denied since it might be a TCP DNS query to a local DNS server. Rejecting it for safety reasons. (in tsocks_connect() at connect.c:193)
curl: (7) Couldn't connect to server
vagrant@ubuntu-sandbox:~$ sudo curl icanhazip.com
curl: (7) Failed to connect to 127.0.0.1 port 9150: Connection refused
```

**Comment by JonZeolla** [comment]
What you were seeing was expected.  `wget` doesn't support socks so it fails closed.  `curl` does but it's falling closed because of the `/etc/tor/torrc` default config.  If you allow local dns resolvers it should work

**Comment by JonZeolla** [comment]
Sounds like it should be documented, I'll update

**Comment by jimmio** [comment]
Found a workaround for using `wget`: `wget --no-proxy icanhazip.com` (returns a known Tor node). Seems like this is good to go with the documentation change and the existing disclaimer.

**Review by jimmio — APPROVED** [review]
Nice, working as expected 👍

**Pull request merged**
